### ISSUE TITLE
Add support of Map 

### ISSUE THREAD

**Issue by DenisPalnitsky** [num30/config#13]

**Comment by d-enk** [comment]
Fix in `v1.4.2` allows to read from a file like this

```yml
Map:
 'key1': 'val1'
 'key2': 'val2'
```

```go
var Config struct {
  Map  map[string]string
}


config.NewConfReader("config").Read(&Config)

```
